# **Linear Algebra with Numpy**

Data Science relies heavily on Linear Algebra. Linear algebra is a branch of mathematics concerned with vector spaces and the mappings between those spaces. Numpy allows us to easily perform linear algebra using the functions it provides. 

## **Scalar, Vector, Matrix, Tensor**

![alt text](https://miro.medium.com/max/617/0*Vh-pKXTJsdL-9FT0.png)

There are different types of objects (or structures) in linear algebra:
+ Scalar: Single number - ndim:0
+ Vector: Array of numbers - ndim: 1
+ Matrix: 2-dimensional array of numbers - ndim: 2
+ Tensor: N-dimensional array of numbers where ndim > 2

In [2]:
import numpy as np

#Creating a scalar
scalar = np.array(43) #ndim - 0

#Creating a vector
vector = np.array([1,2,3]) #ndim - 1

#Creating a matrix
matrix = np.array([[1,2,3],[4,5,6]]) #ndim - 2

#Creating a tensor
tensor = np.array([[[1,2,3],[4,5,6]], [[1,2,3],[4,5,6]]]) #ndim - 3

In [3]:
print(f"Scalar \n{scalar} \nDimension:{scalar.shape}", end = "\n\n")
print(f"Vector \n{vector} \nDimension:{vector.shape}", end = "\n\n")
print(f"Matrix \n{matrix} \nDimension:{matrix.shape}", end = "\n\n")
print(f"Tensor \n{tensor} \nDimension:{tensor.shape}", end = "\n\n")

Scalar 
43 
Dimension:()

Vector 
[1 2 3] 
Dimension:(3,)

Matrix 
[[1 2 3]
 [4 5 6]] 
Dimension:(2, 3)

Tensor 
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]] 
Dimension:(2, 2, 3)



### **Special types of matrices**

In [4]:
#Identity matrix is a square matrix 
#that contains ones on the main diagonal and zeros in all other positions.
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [5]:
#Diagnol matrix is a square matrix
#that contains elements in the diagnol alone
np.diag((1,2,3))

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

### **Transpose**

One of the basic operations on matrices is transpose which means switching rows and columns.

In [6]:
print(f"Vector:\n{vector}, Shape:{vector.shape}")
print(f"Transposed Vector: \n{vector.T}", end = "\n\n")

print(f"Matrix: \n{matrix}")
print(f"Transposed Matrix: \n{matrix.T}", end = "\n\n")

print(f"Tensor: \n{tensor}")
print(f"Transposed Tensor: \n{tensor.T}", end = "\n\n")

Vector:
[1 2 3], Shape:(3,)
Transposed Vector: 
[1 2 3]

Matrix: 
[[1 2 3]
 [4 5 6]]
Transposed Matrix: 
[[1 4]
 [2 5]
 [3 6]]

Tensor: 
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
Transposed Tensor: 
[[[1 1]
  [4 4]]

 [[2 2]
  [5 5]]

 [[3 3]
  [6 6]]]



### **Basic properties of Linear Algebra structures**

Numpy has itself a functinality for Linear Algebra. To acess it, you need to call np.linalg.__()

In [7]:
A = np.array([[6, 1, 1],
              [4, -2, 5],
              [2, 8, 7]])
 
# Rank of a matrix
print("Rank of A:", np.linalg.matrix_rank(A))
 
# Trace of matrix A
print("\nTrace of A:", np.trace(A))
 
# Determinant of a matrix
print("\nDeterminant of A:", np.linalg.det(A))
 
# Inverse of matrix A
print("\nInverse of A:\n", np.linalg.inv(A))
 
print("\nMatrix A raised to power 3:\n",
           np.linalg.matrix_power(A, 3))

Rank of A: 3

Trace of A: 11

Determinant of A: -306.0

Inverse of A:
 [[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]

Matrix A raised to power 3:
 [[336 162 228]
 [406 162 469]
 [698 702 905]]


## **2) Vector Operations**

### **Element wise operations**

In [8]:
vector * scalar

array([ 43,  86, 129])

In [9]:
vector + scalar

array([44, 45, 46])

In [10]:
vector / scalar

array([0.02325581, 0.04651163, 0.06976744])

In [11]:
vector + vector

array([2, 4, 6])

### **Dot Product**

**Dot product between scalars returns a scalar**

In [15]:
#dot product between scalars
np.dot(np.array(10), np.array(30))

300

**Dot product between vectors returns a scalar - it results in inner product of the vectors**

In [12]:
#dot product between two vectors always returns a scaler
np.dot(vector,np.array([5,6,7]))

38

In [13]:
vector.shape

(3,)

**Dot product between 2D arrays returns a 2D array - it results in matrix multiplication**

In [16]:
#2D array a
a = np.array([[1,2],[2,3]])
#2D array b
b = np.array([[4,5],[6,7]])

#dot product between two matrices
np.dot(a,b)

array([[16, 19],
       [26, 31]])

**Dot product between different dimensions**

In such a case, the second dimension of the first array and the first dimension of the second array must be the same. 

In [14]:
#NOTE - np. dot is different from element wise multiplication denoted by "*"
np.dot(vector, np.array([[5,6,7],[8,9,10]]))

ValueError: shapes (3,) and (2,3) not aligned: 3 (dim 0) != 2 (dim 0)

In [19]:
np.dot(np.array([[5,6,7],[8,9,10]]),vector)

array([38, 56])

## **3) Matrix Operations**

Matrix multiplication of two matrices is based on dot products of rows of one matrix with the columns of other matrix.

![alt text](https://imgr.search.brave.com/AfSQ7rMzrFd_81_MAHy_-zm2nupVXjX3POJUTgefHyM/fit/1200/623/no/1/aHR0cHM6Ly9taXJv/Lm1lZGl1bS5jb20v/bWF4LzM2ODgvMSpE/XzF0YnZfd05GSi1y/cnJlbUFHWDRRLnBu/Zw)

In [15]:
A1 = np.arange(4,8).reshape(2,2)
A2 = np.arange(8,12).reshape(2,2)

print(f"A1 : \n{A1}", end = "\n\n")
print(f"A2 : \n{A2}", end = "\n\n")
print("Matrix Multiplication result: ")
print(np.matmul(A1,A2)) #you can also do A1 @ A2

A1 : 
[[4 5]
 [6 7]]

A2 : 
[[ 8  9]
 [10 11]]

Matrix Multiplication result: 
[[ 82  91]
 [118 131]]


Matrix multiplication is not commutative which means we cannot switch the order of matrices in the multiplication. Thus, AB is not equal to BA. When we multiply a matrix with its inverse, we get the identity matrix.

In [16]:
A1 = np.arange(4,8).reshape(2,2)
A1_inverse = np.linalg.inv(A1)
A1 @ A1_inverse

array([[ 1.00000000e+00,  0.00000000e+00],
       [-1.77635684e-15,  1.00000000e+00]])