# **Fundamentals of Numpy**

### **Creating Numpy ndarray object**

NumPy’s main object is the homogeneous multidimensional array. NumPy’s array class is called ndarray. It is also known by the alias array. 

Note that numpy.array is not the same as the Standard Python Library class array.array, which only handles one-dimensional arrays and offers less functionality.

There are 6 general mechanisms for creating arrays:

1. Conversion from other Python structures (i.e. lists and tuples)
2. Intrinsic NumPy array creation functions (e.g. arange, ones, zeros, etc.)
3. Replicating, joining, or mutating existing arrays
4. Reading arrays from disk, either from standard or custom formats
5. Creating arrays from raw bytes through the use of strings or buffers
6. Use of special library functions (e.g., random)

In [27]:
#Importing numpy libray as numpy
import numpy as np

### **Converting Python sequences to NumPy Arrays**

In [28]:
#Creating ndarray object
a = np.array([1, 2, 3])
b = np.array([1., 2., 3.])

In [29]:
#Printing dtype - data type of the array
print(f"Type of a elements is {a.dtype}.")
print(f"Type of b elements is {b.dtype}.")

Type of a elements is int64.
Type of b elements is float64.


In [30]:
try:
    a = np.array(1, 2, 3, 4)    # WRONG
except Exception as e:
    print(e)

array() takes from 1 to 2 positional arguments but 4 were given


In [31]:
a = np.array([1, 2, 3, 4])  # RIGHT
a

array([1, 2, 3, 4])

### **Intrinsic NumPy array creation functions**

#### **np.arange - Return evenly spaced values within a given interval.**

In [32]:
#numpy.arange creates arrays with regularly incrementing values
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
#using numpy.arange to mention dtype
np.arange(2, 10, dtype=float)

array([2., 3., 4., 5., 6., 7., 8., 9.])

In [34]:
#best practice for numpy.arange is to use integer start, end, and step values
np.arange(2, 3, 0.1)

array([2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9])

#### **np.linspace - Return evenly spaced numbers over a specified interval.**

In [35]:
np.linspace(0,10,10, endpoint = False) # (end - start) + 1/ no. of points

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [36]:
np.linspace(0,10,11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [37]:
#numpy.linspace will create arrays with a specified number of elements, 
#and spaced equally between the specified beginning and end values.
np.linspace(1., 4., 6)

array([1. , 1.6, 2.2, 2.8, 3.4, 4. ])

**np.eye - Return a 2-D array with ones on the diagonal and zeros elsewhere.**

In [38]:
#np.eye(n, m) defines a 2D identity 
#matrix. The elements where i=j (row index and column index are equal) 
#are 1 and the rest are 0
np.eye(3,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

**np.diag - Extract a diagonal or construct a diagonal array.**

In [39]:
#numpy.diag can define either a square 2D array with given values along the diagonal 
#or if given a 2D array returns a 1D array that is only the diagonal elements.
np.diag([1, 2, 3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

**np.zeros - Return a new array of given shape and type, filled with zeros.**

In [40]:
#numpy.zeros will create an array filled with 0 values with the specified shape. 
np.zeros((2, 3, 2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

**np.ones - Return a new array of given shape and type, filled with ones.**

In [41]:
#numpy.ones will create an array filled with 1 values. It is identical to zeros
np.ones((2, 3, 2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

### **Replicating, joining, or mutating existing arrays**

In [42]:
#Without using numpy.copy()

a = np.array([1, 2, 3, 4, 5, 6])
#Slicing array
b = a[:2]
b+=1
print('a =', a, '; b =', b)

#NOTE how a also changed. In order to make sure that this doesn't happen, you need to do a copy()

a = [2 3 3 4 5 6] ; b = [2 3]


In [43]:
#Using numpy.copy()

a = np.array([1, 2, 3, 4])
b = a[:2].copy()
b += 1
print('a = ', a, 'b = ', b)

a =  [1 2 3 4] b =  [2 3]


In [44]:
#There are a number of routines to join existing arrays 
#e.g. numpy.vstack, numpy.hstack, and numpy.block.

A = np.ones((2, 2))
B = np.eye(2, 2)
C = np.zeros((2, 2))
D = np.diag((-3, -4))

print(f"Using vstack - \n{np.vstack((A,B))}", end = '\n\n')
print(f"Using hstack - \n{np.hstack((A,B))}", end = '\n\n')
print(f"Using block - \n{ np.block([A, B,C, D])}", end = '\n\n')

Using vstack - 
[[1. 1.]
 [1. 1.]
 [1. 0.]
 [0. 1.]]

Using hstack - 
[[1. 1. 1. 0.]
 [1. 1. 0. 1.]]

Using block - 
[[ 1.  1.  1.  0.  0.  0. -3.  0.]
 [ 1.  1.  0.  1.  0.  0.  0. -4.]]



## **Different dimensions & shape in arrays**

A dimension in arrays is one level of array depth (nested arrays).

In [45]:
#0-D array or scaler
zero_d = np.array(34)
#1-D array 
one_d = np.array([1, 2, 3, 4, 5])
#2-D array 
two_d = np.array([[1, 2, 3], [4, 5, 6]])
#3-D array 
three_d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(f"Dimension {zero_d.ndim} and shape {zero_d.shape} : \n {zero_d}", end = '\n\n')
print(f"Dimension {one_d.ndim} and shape {one_d.shape} : \n {one_d}", end = '\n\n')
print(f"Dimension {two_d.ndim} and shape {two_d.shape} : \n {two_d}", end = '\n\n')
print(f"Dimension {three_d.ndim} and shape {three_d.shape} : \n {three_d}", end = '\n\n')

Dimension 0 and shape () : 
 34

Dimension 1 and shape (5,) : 
 [1 2 3 4 5]

Dimension 2 and shape (2, 3) : 
 [[1 2 3]
 [4 5 6]]

Dimension 3 and shape (2, 2, 3) : 
 [[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]



### **Using reshape**

You can use numpy.reshape for giving a new shape to your array without changing the data.

Note: The new shape should be compatible with the original shape. No. of elements before and after reshape must remain the same. 

In [46]:
a = np.arange(6).reshape((3, 2))
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [47]:
np.reshape(a, (2, 3)) 

array([[0, 1, 2],
       [3, 4, 5]])

In [48]:
np.reshape(a, 6)

array([0, 1, 2, 3, 4, 5])

In [49]:
np.reshape(a, (3,-1)) # the unspecified value is inferred to be 2

array([[0, 1],
       [2, 3],
       [4, 5]])

In [50]:
np.reshape(a, (4,-1)) #incompatible shape

ValueError: cannot reshape array of size 6 into shape (4,newaxis)

### **Using flatten**

Numpy.flatten() returns the copy of the array converted into 1D. 

In [51]:
#Using ndarray.flatten()
a = np.array([[1,2], [3,4]])
print(a)
a.flatten()

[[1 2]
 [3 4]]


array([1, 2, 3, 4])

## **Slicing & Accessing**



The basic slice syntax is i:j:k where i is the starting index, j is the stopping index, and k is the step.

In [67]:
# Initializing an array
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
 
#Single Indexing
print(x[4])

#Slicing - getting all the elements
print(x[:])

#Slicing - from element index 3 to 7
print(x[3:8])

# Index values can be negative
print(x[np.array([1, 3, -3])])

5
[1 2 3 4 5 6 7 8 9]
[4 5 6 7 8]
[2 4 7]


In [52]:
#Initializing an array - 2D
x = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#Example of slicing
x[1:7:2]

array([1, 3, 5])

Ellipsis expands to the number of : objects needed for the selection tuple to index all dimensions. In most cases, this means that length of the expanded selection tuple is x.ndim. There may only be a single ellipsis present.

In [53]:
#Initializing an array
x = np.array([[[1],[2],[3]], [[4],[5],[6]]])

#Takes all the dimensions till the last dimension
x[...,0]

array([[1, 2, 3],
       [4, 5, 6]])

## **Broadcasting**

The term broadcasting describes how numpy treats arrays with different shapes during arithmetic operations. 

The smaller array is “broadcast” across the larger array so that they have compatible shapes.

This is why we don't have to loop through the  elements to do element wise addition or any other operation.

![alt text](https://www.educative.io/api/edpresso/shot/4760396746457088/image/4638672331735040)

In [78]:
a = np.array([1.0, 2.0, 3.0])
b = 2
a * b

array([2., 4., 6.])

In [86]:
x = np.arange(4)
xx = x.reshape(4,1)
y = np.ones(5)
z = np.ones((3,4))

print(f"x array: \n{x}\n\n")
print(f"xx array: \n{xx}\n\n")
print(f"y array: \n{y}\n\n")
print(f"z array: \n{z}\n\n")

x array: 
[0 1 2 3]


xx array: 
[[0]
 [1]
 [2]
 [3]]


y array: 
[1. 1. 1. 1. 1.]


z array: 
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]




In [90]:
#Does not work because of incompatible shapes
x + y

ValueError: operands could not be broadcast together with shapes (4,) (5,) 

In [91]:
#Works because of compatible shapes
xx + y

array([[1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.]])

In [92]:
#Works because of compatible shapes
x + z

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])